name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node 20
        uses: actions/setup-node@v1
        with:
          node-version: 20.x

      - name: Install dependencies
        run: npm ci

      - name: Format
        run: npm run format

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm test

      - name: Build
        run: npm run build
